eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:19527/eureka/
  instance:
    hostname: localhost
server:
# 服务端口
  port: 20000
spring:
  application:
    name: monitor
    security.basic.enabled: false
    turbine:
      aggregator:
        clusterConfig: default
      appConfig: DEMO1,DEMO2
      cluster-name-expression: new String("default")