spring:
  application:
    name: gateway
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: http://localhost:19527/eureka/
zuul:
  routes:
    demo1:
      path: /demo1/**
      serviceId: demo1
    demo2:
      path: /demo2/**
      serviceId: demo2
